### ISSUE TITLE
Implement Basic RRT

### ISSUE THREAD

**Issue by ManuelDCR** [stephanheinemann/worldwind#13]
Implement a simple Rapidly-exploring Random Tree (RRT) planner for a continuous environment.

**Comment by stephanheinemann** [comment]
The RRT* implementation does not achieve optimality (in the probabilistic sense) in its current implementation. Choosing the best parent (local optimum) does not necessarily lead to a global improvement. Changing parents changes the ETOs of children and
their dependents (ETO propagation). As a result, the costs of already established sub-tree edges change based on the propagated ETOs. This may lead to a cost regression in the rewired tree. In general there does not appear to be a naive solution for RRT* in 4D: Parent regression could lead to sub-tree improvement, parent improvement could lead to sub-tree regression. Even if the improvement is constrained to a full sub-tree improvement, the full sub-tree improvement could lead to global regression and a full sub-tree regression could lead to a global improvement.

**Comment by stephanheinemann** [comment]
The multi-part plans generated by ARRT are currently invalid: Improved parts can only be concatenated if they are based on the same ETO of their connecting waypoints. There are different approaches to achieve this (without considering ETO slots as discussed in #24):
(1) Parts may be fully improved sequentially with fixed ETOs established before proceeding to the next part (subsequent parts may degrade or become infeasible as a result)
(2) Parts may be partially improved where only a complete trajectory improvement (overall cost) constitutes an improvement (intermediate parts may degrade)
(3) Parts may be partially improved where only the improvement of each part constitutes an improvement (unlikely to achieve any improvement if only one part degrades)

ARA* and AD* apply option (1). However, option (2) is probably the best trade-off for multi-part plans and should be considered.
