### ISSUE TITLE
Solve NASA Worldwind servers connection problem

### ISSUE THREAD

**Issue by ManuelDCR** [stephanheinemann/worldwind#14]
NASA Worldwind servers have been updated to version 2.1.0 on Dec 13, 2016. As described [here](https://github.com/NASAWorldWind/WorldWindJava/releases/), map services were updated to use HTTPS protocol and a redirect was set. However, Java doesn't automatically redirect from the HTTP pages.

> With the release of v2.1.0 all NASA World Wind map services (imagery, terrain, placenames, etc.) require HTTPS connections. Existing versions of World Wind (including v2.0.0) will not connect unless map service links are updated to use the HTTPS protocol. There is an HTTP to HTTPS redirect in place for all NASA World Wind map services, but the Java VM will not automatically follow the redirect. The requirement to host map services exclusively through HTTPS is a U.S. Government mandate.

Currently the program is built using Woorldwind v2.0.0. There isn't any maven release for version 2.1.0 yet, but the [issue](https://github.com/NASAWorldWind/WorldWindJava/issues/84) is under development.

**Comment by stephanheinemann** [comment]
I have released a NASA WorldWind Java 2.2.0 Maven project on the central repository which can now be used.
#https://github.com/NASAWorldWind/WorldWindJava/issues/84
