### ISSUE TITLE
Identifying/Correcting some minor errors in code

### ISSUE THREAD

**Issue by ManuelDCR** [stephanheinemann/worldwind#17]
This issued is opened to identify minor bugs detected in code developed in previous features.

**Comment by ManuelDCR** [comment]
The waypoints are not correctly sorted in the UI by designation. It is ordering the string, menaing that when there are more than 10 waypoints it is ordered like 0.0, 0.1, 0.10, 0.11, 0.2, 0.3 ...
Suggested solution: use a comparator that extracts numerical values from string
```

Collections.sort(strings, new Comparator<String>() {
    public int compare(String o1, String o2) {
        return extractInt(o1) - extractInt(o2);
    }

    int extractInt(String s) {
        String num = s.replaceAll("\\D", "");
        // return 0 if no digits found
        return num.isEmpty() ? 0 : Integer.parseInt(num);
    }
});
```

**Comment by ManuelDCR** [comment]
The computation of estimated time has no intermediate rate of climb. It either goes at cruise rate of climb or at maximum rate of climb. This means that for very similar linear distances, great differences in time may be observed.
https://github.com/stephanheinemann/worldwind/blob/01192022bdf07ae7a9dfe3eb51b7e325672c1f53/src/main/java/com/cfar/swim/worldwind/aircraft/Capabilities.java#L411-L438
Similar situation happens for Descent.

Suggestion: If CruiseRateOfClimb is not enough, try to go at the RateOfClimb corresponding to a direct path from source to goal. Check feasibility by comparing the resulting angle with the maximumAngleOfClimb.

**Comment by stephanheinemann** [comment]
> The waypoints are not correctly sorted in the UI by designation. It is ordering the string, menaing that when there are more than 10 waypoints it is ordered like 0.0, 0.1, 0.10, 0.11, 0.2, 0.3 ...
> Suggested solution: use a comparator that extracts numerical values from string
> 
> ```
> 
> Collections.sort(strings, new Comparator<String>() {
>     public int compare(String o1, String o2) {
>         return extractInt(o1) - extractInt(o2);
>     }
> 
>     int extractInt(String s) {
>         String num = s.replaceAll("\\D", "");
>         // return 0 if no digits found
>         return num.isEmpty() ? 0 : Integer.parseInt(num);
>     }
> });
> ```

I am unable to reproduce the issue in the current development branch. The plan view appears to correctly populate all waypoints and their children even for more than 10 children.

**Comment by stephanheinemann** [comment]
> The computation of estimated time has no intermediate rate of climb. It either goes at cruise rate of climb or at maximum rate of climb. This means that for very similar linear distances, great differences in time may be observed.
> 
> https://github.com/stephanheinemann/worldwind/blob/01192022bdf07ae7a9dfe3eb51b7e325672c1f53/src/main/java/com/cfar/swim/worldwind/aircraft/Capabilities.java#L411-L438
> 
> Similar situation happens for Descent.
> 
> Suggestion: If CruiseRateOfClimb is not enough, try to go at the RateOfClimb corresponding to a direct path from source to goal. Check feasibility by comparing the resulting angle with the maximumAngleOfClimb.

This issue relates to the introduction of a separate isFeasible() method and should be addressed when integrating the PRM/RTT algorithms. The performance related to the required climb gradient does not equal the performance related to the maximum climb gradient and the computation has to be reviewed.
