### ISSUE TITLE
BeanInfo Implementation

### ISSUE THREAD

**Issue by ManuelDCR** [stephanheinemann/worldwind#18]
Registries should pass more information for the UI to show the user. The information in the beans can be complemented with the creation of BeanInfo classes.

Each bean can have a BeanInfo class associated with it if it is in the same package and as the same name + BeanInfo.

**Comment by stephanheinemann** [comment]
This implementation will likely have to be changed as UI components should not be part of the Core.
Currently the core imports org.controlsfx.controlsfx which is a UI component and belongs in the UI only.
I will keep the issue open until fully reviewed.

**Comment by ManuelDCR** [comment]
From my review we are using an import of "org.controlsfx.property.BeanProperty" which is only required to define the category of each property. If we remove the categories there will only be dependencies for "java.beans". However, categories are very important to properly organize the display in the UI.

**Comment by stephanheinemann** [comment]
Very good point. I simplified and integrated the solution into the development branch. Any information shown on the UI has to be externalized though. I added a dictionary resource bundle for that purpose. It can also be evaluated if the packages should be split and bean info classes located in the UI instead. I will keep that in mind for future releases.

**Comment by stephanheinemann** [comment]
Move the dictionary resource bundles from the SAFCS Core to the SAFCS UI.
