### ISSUE TITLE
ObstacleCylinder embed into PlanningGrid

### ISSUE THREAD

**Issue by henriquebferreira** [stephanheinemann/worldwind#22]
The intersection method for embedding ObstacleCylinder such as a thunderstorm into a PlanningGrid is not correctly implemented. The cylinder is transformed into a bounding box, which increases the area of effect of the obstacle.

![embedbefore](https://user-images.githubusercontent.com/37160086/51083084-d230bf80-170b-11e9-9a5b-f7b5ed86b9c5.png)

**Comment by henriquebferreira** [comment]
A new intersection method was developed to solve the issue presented.

![embedafter](https://user-images.githubusercontent.com/37160086/51083096-04dab800-170c-11e9-915e-4df0b37f30c0.png)

**Comment by stephanheinemann** [comment]
Good catch! I integrated a simplified version of the fix into the development branch. Since it is a box-cylinder intersection check, it belongs into the more basic geometric box class from which a planning grid is derived.

**Comment by stephanheinemann** [comment]
The algorithm does not appear to work correctly always. I could observe several situations in which obstacles are not correctly embedded. In these cases none or only one of the grid voxels was affected by the embedding. The solution has to be reviewed more carefully.

**Comment by stephanheinemann** [comment]
It might be easier to use an existing Java GJK library for specific collision checks instead.
